baseurl: /boulder
permalink: pretty
markdown: kramdown
paginate: 5
repo: boulder
github_org: maptime
maptime:
  chapter: MaptimeBoulder
  twitter: MaptimeBoulder
  #disqus: YOUR DISQUS USERNAME

future: true
gems:
  - jekyll-feed
